# Generated by Django 5.0.1 on 2024-01-24 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Курс валюты')),
                ('currency', models.CharField(max_length=3, verbose_name='Код валюты')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
            ],
            options={
                'verbose_name': 'курс валюты',
                'verbose_name_plural': 'Курсы валют',
            },
        ),
    ]
